// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhtribqzuugkordyxvzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodHJpYnF6dXVna29yZHl4dnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTM2NTAsImV4cCI6MjA2NjA4OTY1MH0.icvh9wPJ0kwDnAhJeWRIUdyWuz0mf5YPbqDz-6gPADg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);